
version: '3.8'

services:
  fastapi-ml:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Method 1: Use env_file to load from .env file
    env_file:
      - .env
    # Method 2: You can also explicitly set environment variables
    environment:
      - ENV=development
      - TESSERACT_PATH=/usr/bin/tesseract
      - GOOGLE_APPLICATION_CREDENTIALS=your-google-service-account.json
      - GROQ_API_KEY=GROQ_API_KEY
    volumes:
      # Mount code for development (remove for production)
      - .:/app
      # Method 3: Mount .env file directly (alternative approach)
      # - ./.env:/app/.env:ro
      # Persistent volume for any data/models
      - ml_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ml_data: